const DB={"1005": {"name": "Amoníaco, anhidro", "containers": {"rail": {"label": "Carrotanque de ferrocarril", "iso": 300, "day": [1.9, 1.5, 1.1], "night": [4.5, 2.5, 1.4]}, "truck": {"label": "Autotanque o remolque", "iso": 150, "day": [0.9, 0.5, 0.4], "night": [2.0, 0.8, 0.6]}, "farm": {"label": "Tanque de agricultura", "iso": 60, "day": [0.5, 0.3, 0.3], "night": [1.4, 0.3, 0.3]}, "smallmulti": {"label": "Múltiples cilindros pequeños", "iso": 30, "day": [0.3, 0.2, 0.1], "night": [0.7, 0.3, 0.2]}}}, "1017": {"name": "Cloro", "containers": {"rail": {"label": "Carrotanque de ferrocarril", "iso": 1000, "day": [10.1, 6.8, 5.3], "night": ["11.0+", 9.2, 6.9]}, "truck": {"label": "Autotanque o remolque", "iso": 600, "day": [5.8, 3.4, 2.9], "night": [6.7, 5.0, 4.1]}, "tonmulti": {"label": "Múltiples cilindros tonel", "iso": 300, "day": [2.1, 1.3, 1.0], "night": [4.0, 2.4, 1.3]}, "small_or_ton": {"label": "Múltiples cilindros pequeños o un cilindro tonel", "iso": 150, "day": [1.5, 0.8, 0.5], "night": [2.9, 1.3, 0.6]}}}, "1040": {"name": "Óxido de etileno / con nitrógeno", "containers": {"rail": {"label": "Carrotanque de ferrocarril", "iso": 200, "day": [1.6, 0.8, 0.7], "night": [3.3, 1.4, 0.8]}, "truck": {"label": "Autotanque o remolque", "iso": 100, "day": [0.9, 0.5, 0.4], "night": [2.0, 0.7, 0.4]}, "small_or_ton": {"label": "Múltiples cilindros pequeños o un cilindro tonel", "iso": 30, "day": [0.4, 0.2, 0.1], "night": [0.9, 0.3, 0.2]}}}, "1050": {"name": "Cloruro de hidrógeno, anhidro / UN2186 refrigerado", "containers": {"rail": {"label": "Carrotanque de ferrocarril", "iso": 500, "day": [3.9, 2.1, 1.8], "night": [10.1, 3.5, 2.3]}, "truck": {"label": "Autotanque o remolque", "iso": 200, "day": [1.5, 0.8, 0.6], "night": [3.9, 1.5, 0.8]}, "tonmulti": {"label": "Múltiples cilindros tonel", "iso": 30, "day": [0.4, 0.2, 0.1], "night": [1.1, 0.3, 0.2]}, "small_or_ton": {"label": "Múltiples cilindros pequeños o un cilindro tonel", "iso": 30, "day": [0.3, 0.2, 0.1], "night": [0.9, 0.3, 0.2]}}}, "1052": {"name": "Fluoruro de hidrógeno, anhidro", "containers": {"rail": {"label": "Carrotanque de ferrocarril", "iso": 500, "day": [3.5, 2.1, 1.8], "night": [6.6, 3.1, 2.0]}, "truck": {"label": "Autotanque o remolque", "iso": 200, "day": [2.0, 1.0, 0.9], "night": [3.7, 1.6, 0.9]}, "small_or_ton": {"label": "Múltiples cilindros pequeños o un cilindro tonel", "iso": 100, "day": [0.8, 0.4, 0.3], "night": [1.7, 0.5, 0.3]}}}, "1079": {"name": "Dióxido de azufre", "containers": {"rail": {"label": "Carrotanque de ferrocarril", "iso": 1000, "day": ["11.0+", "11.0+", 7.2], "night": ["11.0+", "11.0+", 10.1]}, "truck": {"label": "Autotanque o remolque", "iso": 1000, "day": ["11.0+", 6.2, 5.3], "night": ["11.0+", 8.2, 6.2]}, "tonmulti": {"label": "Múltiples cilindros tonel", "iso": 500, "day": [5.4, 2.4, 1.8], "night": [7.8, 4.2, 2.9]}, "small_or_ton": {"label": "Múltiples cilindros pequeños o un cilindro tonel", "iso": 200, "day": [3.2, 1.5, 1.1], "night": [5.8, 2.5, 1.5]}}}};
const $=id=>document.getElementById(id);
const winds={light:0,moderate:1,strong:2};
let current=null;
function fillUN(){ $('un').innerHTML=Object.entries(DB).map(([u,v])=>`<option value="${u}">UN${u} — ${v.name}</option>`).join(''); fillContainers()}
function fillContainers(){let s=DB[$('un').value];$('container').innerHTML=Object.entries(s.containers).map(([k,v])=>`<option value="${k}">${v.label}</option>`).join('')}
$('un').onchange=fillContainers;
$('windPreset').onchange=e=>{if(e.target.value!=='')$('bearing').value=e.target.value}
$('gps').onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>{$('lat').value=p.coords.latitude.toFixed(7);$('lon').value=p.coords.longitude.toFixed(7)},e=>alert('No fue posible obtener el GPS: '+e.message),{enableHighAccuracy:true}):alert('GPS no disponible');
$('calc').onclick=()=>{
 const u=$('un').value,c=$('container').value,p=$('period').value,w=$('wind').value;
 const row=DB[u].containers[c], val=row[p][winds[w]];
 current={un:u,name:DB[u].name,container:c,containerLabel:row.label,period:p,wind:w,bearing:+$('bearing').value,lat:+$('lat').value,lon:+$('lon').value,isolation_m:row.iso,protective_km:val};
 $('chemical').textContent=`UN${u} — ${DB[u].name}`;
 $('scenario').textContent=`${row.label} · ${p==='day'?'Día':'Noche'} · viento ${w==='light'?'leve':w==='moderate'?'moderado':'fuerte'}`;
 $('iso').textContent=`${row.iso} m`;
 $('protect').textContent=`${val} km`;
 $('warn').innerHTML=(String(val).includes('+')?'<b>Distancia con “+”:</b> puede ser mayor en ciertas condiciones atmosféricas.<br>':'')+'Aproxímese desde barlovento, terreno elevado y corriente arriba. Confirme el producto, el recipiente, la evolución de la fuga y la dirección real del viento.';
 document.querySelectorAll('.result').forEach(x=>x.style.display='block'); draw(); window.scrollTo({top:$('result').offsetTop-80,behavior:'smooth'})
};
function draw(){
 const svg=$('diagram'),cx=350,cy=240,iso=55;
 let from=((current.bearing%360)+360)%360, down=(from+180)%360, a=(down-90)*Math.PI/180;
 let ux=Math.cos(a),uy=Math.sin(a),px=-uy,py=ux,L=245,w=105;
 let tipx=cx+ux*L,tipy=cy+uy*L,b1x=cx+px*25,b1y=cy+py*25,b2x=cx-px*25,b2y=cy-py*25,t1x=tipx+px*w,t1y=tipy+py*w,t2x=tipx-px*w,t2y=tipy-py*w;
 svg.innerHTML=`<defs><marker id="arr" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#1565c0"/></marker></defs>
 <polygon points="${b1x},${b1y} ${t1x},${t1y} ${t2x},${t2y} ${b2x},${b2y}" fill="#ffd54f" fill-opacity=".55" stroke="#f9a825" stroke-width="3"/>
 <circle cx="${cx}" cy="${cy}" r="${iso}" fill="#ef5350" fill-opacity=".45" stroke="#c62828" stroke-width="4"/>
 <line x1="${cx-ux*120}" y1="${cy-uy*120}" x2="${cx+ux*160}" y2="${cy+uy*160}" stroke="#1565c0" stroke-width="6" marker-end="url(#arr)"/>
 <circle cx="${cx}" cy="${cy}" r="7" fill="#111"/>
 <text x="${cx}" y="${cy-70}" text-anchor="middle" font-size="18" font-weight="800">Punto de liberación</text>
 <text x="${tipx}" y="${tipy-12}" text-anchor="middle" font-size="17" font-weight="800">Sotavento ${current.protective_km} km</text>
 <text x="${cx-ux*145}" y="${cy-uy*145-10}" text-anchor="middle" font-size="16" font-weight="700">Barlovento</text>
 <text x="18" y="452" font-size="14">Diagrama no cartográfico · rumbo de dispersión ${(current.bearing+180)%360}°</text>`;
}
function dest(lat,lon,bearing,dist){const R=6378137,d=dist/R,b=bearing*Math.PI/180,p1=lat*Math.PI/180,l1=lon*Math.PI/180;const p2=Math.asin(Math.sin(p1)*Math.cos(d)+Math.cos(p1)*Math.sin(d)*Math.cos(b));const l2=l1+Math.atan2(Math.sin(b)*Math.sin(d)*Math.cos(p1),Math.cos(d)-Math.sin(p1)*Math.sin(p2));return [p2*180/Math.PI,l2*180/Math.PI]}
function circle(r){let a=[];for(let b=0;b<=360;b+=5){let [la,lo]=dest(current.lat,current.lon,b,r);a.push(`${lo},${la},0`)}return a.join(' ')}
function sector(r){let down=(current.bearing+180)%360,a=[`${current.lon},${current.lat},0`];for(let i=0;i<=36;i++){let b=down-22.5+45*i/36,[la,lo]=dest(current.lat,current.lon,b,r);a.push(`${lo},${la},0`)}a.push(`${current.lon},${current.lat},0`);return a.join(' ')}
$('kml').onclick=()=>{if(!current)return;let km=parseFloat(String(current.protective_km).replace('+',''));let k=`<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>UN${current.un} - Respuesta inicial</name><Placemark><name>Punto de liberación</name><Point><coordinates>${current.lon},${current.lat},0</coordinates></Point></Placemark><Placemark><name>Aislamiento inicial ${current.isolation_m} m</name><Style><LineStyle><color>ff0000ff</color><width>3</width></LineStyle><PolyStyle><color>550000ff</color></PolyStyle></Style><Polygon><outerBoundaryIs><LinearRing><coordinates>${circle(current.isolation_m)}</coordinates></LinearRing></outerBoundaryIs></Polygon></Placemark><Placemark><name>Acción protectora ${current.protective_km} km</name><Style><LineStyle><color>ff00ffff</color><width>3</width></LineStyle><PolyStyle><color>5500ffff</color></PolyStyle></Style><Polygon><outerBoundaryIs><LinearRing><coordinates>${sector(km*1000)}</coordinates></LinearRing></outerBoundaryIs></Polygon></Placemark></Document></kml>`;download(`UN${current.un}_respuesta_inicial.kml`,k,'application/vnd.google-earth.kml+xml')};
$('json').onclick=()=>current&&download(`UN${current.un}_incidente.json`,JSON.stringify(current,null,2),'application/json');
function download(name,data,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
fillUN();